# Development Profile
server.port=8080
spring.profiles.active=dev

# Database - Development
spring.datasource.url=jdbc:mysql://localhost:3306/mhz_emporio_gourmet_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Logging
logging.level.root=INFO
logging.level.com.mhz.api=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG